concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

name: "Publish to Cachix"
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "*.nix"
      - "Cargo.lock"
      - "flake.lock"

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    if: secrets.CACHIX_TOKEN != null
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: "${{ vars.CACHIX_OWNER || github.repository_owner }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - run: nix build --no-update-lock-file --no-link -L .#zed-editor
      - run: nix shell .#zed-editor --command echo Ok
      - run: |
          ./tooling/nix/update-pins.sh
          echo "```json" >> $GITHUB_STEP_SUMMARY
          cat ./tooling/nix/pins.json >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        if: failure()
      - uses: parkerbxyz/suggest-changes@v1
        if: failure()
        with:
          comment: "The Nix pins are out of date, please update them."
