concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

name: "Publish to Cachix"
on:
  pull_request:
  merge_group:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        if: github.event_name != 'pull_request'
        with:
          name: "${{ vars.CACHIX_OWNER || github.repository_owner }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - run: nix build --no-update-lock-file --no-link -L .#zed-editor
      - run: nix shell .#zed-editor nixpkgs#bash --command echo Ok
