concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

name: "Publish to Cachix"
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**/*.nix"
      - "Cargo.lock"
      - "flake.lock"
      - "**/pins.json"

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        if: github.event_name != 'pull_request'
        with:
          name: "${{ vars.CACHIX_OWNER || github.repository_owner }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - run: |
          nix build --no-update-lock-file --no-link -L .#zed-editor
          nix shell .#zed-editor --command echo OK
      - run: |
          ./tooling/nix/update-pins.sh
          echo "`./tooling/nix/pins.json`:" >> $GITHUB_STEP_SUMMARY
          echo "```json" >> $GITHUB_STEP_SUMMARY
          cat ./tooling/nix/pins.json >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        if: failure()
      - uses: getsentry/action-git-diff-suggestions@main
        if: failure()
        with:
          message: "The Nix pins need to be updated"
