name: Sync Fork

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: zed-industries
          base: main
          head: main
